//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo_v3.GDAL {

public enum ViewshedOutputType {
  GVOT_NORMAL = 1,
  GVOT_MIN_TARGET_HEIGHT_FROM_DEM = 2,
  GVOT_MIN_TARGET_HEIGHT_FROM_GROUND = 3
}

}
