//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gView.Plugins.Editor.Plugins.Editor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class globalisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal globalisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gView.Plugins.Editor.Plugins.Editor.globalisation", typeof(globalisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolut X,Y....
        /// </summary>
        internal static string AbsolutXY {
            get {
                return ResourceManager.GetString("AbsolutXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vertex.
        /// </summary>
        internal static string AddVertex {
            get {
                return ResourceManager.GetString("AddVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Part.
        /// </summary>
        internal static string ClosePart {
            get {
                return ResourceManager.GetString("ClosePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deflection....
        /// </summary>
        internal static string Deflection {
            get {
                return ResourceManager.GetString("Deflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta X,Y....
        /// </summary>
        internal static string DeltaXY {
            get {
                return ResourceManager.GetString("DeltaXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction....
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction, Distance....
        /// </summary>
        internal static string DirectionDistance {
            get {
                return ResourceManager.GetString("DirectionDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance....
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance-Direction Tool.
        /// </summary>
        internal static string DistanceDirectionTool {
            get {
                return ResourceManager.GetString("DistanceDirectionTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance-Distance Tool.
        /// </summary>
        internal static string DistanceDistanceTool {
            get {
                return ResourceManager.GetString("DistanceDistanceTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance-Tangent Tool.
        /// </summary>
        internal static string DistanceTangentTool {
            get {
                return ResourceManager.GetString("DistanceTangentTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Part.
        /// </summary>
        internal static string EditPart {
            get {
                return ResourceManager.GetString("EditPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersection Tool.
        /// </summary>
        internal static string IntersectionTool {
            get {
                return ResourceManager.GetString("IntersectionTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middlepoint Tool.
        /// </summary>
        internal static string MiddlepointTool {
            get {
                return ResourceManager.GetString("MiddlepointTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orthogonal.
        /// </summary>
        internal static string Orthogonal {
            get {
                return ResourceManager.GetString("Orthogonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel To.
        /// </summary>
        internal static string ParallelTo {
            get {
                return ResourceManager.GetString("ParallelTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen.
        /// </summary>
        internal static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perpenticula To.
        /// </summary>
        internal static string PerpenticulaTo {
            get {
                return ResourceManager.GetString("PerpenticulaTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Vertex.
        /// </summary>
        internal static string RemoveVertex {
            get {
                return ResourceManager.GetString("RemoveVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to construct cirle 1 - Midpoint.
        /// </summary>
        internal static string S1 {
            get {
                return ResourceManager.GetString("S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set first ray direction or use parallel or perpendicular context menu.
        /// </summary>
        internal static string S10 {
            get {
                return ResourceManager.GetString("S10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set secont ray start point.
        /// </summary>
        internal static string S11 {
            get {
                return ResourceManager.GetString("S11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set second ray direction or use parallel or perpendicular context menu.
        /// </summary>
        internal static string S12 {
            get {
                return ResourceManager.GetString("S12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to construct cirle midpoint.
        /// </summary>
        internal static string S13 {
            get {
                return ResourceManager.GetString("S13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move and click to construct circle raduis.
        /// </summary>
        internal static string S14 {
            get {
                return ResourceManager.GetString("S14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set ray start point.
        /// </summary>
        internal static string S15 {
            get {
                return ResourceManager.GetString("S15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set ray direction or use parallel or perpendicular context menu.
        /// </summary>
        internal static string S16 {
            get {
                return ResourceManager.GetString("S16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move and click to construct circle 1 - Raduis.
        /// </summary>
        internal static string S2 {
            get {
                return ResourceManager.GetString("S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to constuct circle 2 - Midpoint.
        /// </summary>
        internal static string S3 {
            get {
                return ResourceManager.GetString("S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move and click to construct circle 2 -Raduis.
        /// </summary>
        internal static string S4 {
            get {
                return ResourceManager.GetString("S4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to choose result point.
        /// </summary>
        internal static string S5 {
            get {
                return ResourceManager.GetString("S5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set first Point.
        /// </summary>
        internal static string S6 {
            get {
                return ResourceManager.GetString("S6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set second Point.
        /// </summary>
        internal static string S7 {
            get {
                return ResourceManager.GetString("S7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to continue.
        /// </summary>
        internal static string S8 {
            get {
                return ResourceManager.GetString("S8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set first ray start point.
        /// </summary>
        internal static string S9 {
            get {
                return ResourceManager.GetString("S9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment Distance.
        /// </summary>
        internal static string SegmentDistance {
            get {
                return ResourceManager.GetString("SegmentDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment Midpoint.
        /// </summary>
        internal static string SegmentMidpoint {
            get {
                return ResourceManager.GetString("SegmentMidpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment Orthogonal.
        /// </summary>
        internal static string SegmentOrthogonal {
            get {
                return ResourceManager.GetString("SegmentOrthogonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semgent (use Direction).
        /// </summary>
        internal static string SemgentUseDirection {
            get {
                return ResourceManager.GetString("SemgentUseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap To.
        /// </summary>
        internal static string SnapTo {
            get {
                return ResourceManager.GetString("SnapTo", resourceCulture);
            }
        }
    }
}
