//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo_v3.GDAL {

public enum AsyncStatusType {
  GARIO_PENDING = 0,
  GARIO_UPDATE = 1,
  GARIO_ERROR = 2,
  GARIO_COMPLETE = 3
}

}
