//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo_v3.GDAL {

public enum ViewshedMode {
  GVM_Diagonal = 1,
  GVM_Edge = 2,
  GVM_Max = 3,
  GVM_Min = 4
}

}
