//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gView.Globalisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gView.Globalisation.ResNames", typeof(ResNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0}.
        /// </summary>
        internal static string ArgString_Create {
            get {
                return ResourceManager.GetString("ArgString.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new {0}.
        /// </summary>
        internal static string ArgString_New {
            get {
                return ResourceManager.GetString("ArgString.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Menu_Activate {
            get {
                return ResourceManager.GetString("Menu.Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Favorites ....
        /// </summary>
        internal static string Menu_AddToFavorites {
            get {
                return ResourceManager.GetString("Menu.AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Menu_Close {
            get {
                return ResourceManager.GetString("Menu.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Properties....
        /// </summary>
        internal static string Menu_ConnectionProperties {
            get {
                return ResourceManager.GetString("Menu.ConnectionProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Views.
        /// </summary>
        internal static string Menu_DataViews {
            get {
                return ResourceManager.GetString("Menu.DataViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Menu_Delete {
            get {
                return ResourceManager.GetString("Menu.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Map.
        /// </summary>
        internal static string Menu_DeleteMap {
            get {
                return ResourceManager.GetString("Menu.DeleteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Menu_Import {
            get {
                return ResourceManager.GetString("Menu.Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Group.
        /// </summary>
        internal static string Menu_InsertGroup {
            get {
                return ResourceManager.GetString("Menu.InsertGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert New Dataview ....
        /// </summary>
        internal static string Menu_InsertNewDataview {
            get {
                return ResourceManager.GetString("Menu.InsertNewDataview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Layer.
        /// </summary>
        internal static string Menu_LockLayer {
            get {
                return ResourceManager.GetString("Menu.LockLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Properties ....
        /// </summary>
        internal static string Menu_MapProperties {
            get {
                return ResourceManager.GetString("Menu.MapProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata....
        /// </summary>
        internal static string Menu_Metadata {
            get {
                return ResourceManager.GetString("Menu.Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Group.
        /// </summary>
        internal static string Menu_MoveToGroup {
            get {
                return ResourceManager.GetString("Menu.MoveToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Menu_New {
            get {
                return ResourceManager.GetString("Menu.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Map.
        /// </summary>
        internal static string Menu_NewMap {
            get {
                return ResourceManager.GetString("Menu.NewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Service From gView Map ....
        /// </summary>
        internal static string Menu_NewServiceFromMap {
            get {
                return ResourceManager.GetString("Menu.NewServiceFromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options ....
        /// </summary>
        internal static string Menu_Options {
            get {
                return ResourceManager.GetString("Menu.Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties ....
        /// </summary>
        internal static string Menu_Properties {
            get {
                return ResourceManager.GetString("Menu.Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Menu_Remove {
            get {
                return ResourceManager.GetString("Menu.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Menu_Rename {
            get {
                return ResourceManager.GetString("Menu.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scales.
        /// </summary>
        internal static string Menu_Scales {
            get {
                return ResourceManager.GetString("Menu.Scales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Reference System.
        /// </summary>
        internal static string Menu_SpatialReferenceSystem {
            get {
                return ResourceManager.GetString("Menu.SpatialReferenceSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Layer Group.
        /// </summary>
        internal static string Menu_SplitLayerGroup {
            get {
                return ResourceManager.GetString("Menu.SplitLayerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbars.
        /// </summary>
        internal static string Menu_Toolbars {
            get {
                return ResourceManager.GetString("Menu.Toolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock layer.
        /// </summary>
        internal static string Menu_UnlockLayer {
            get {
                return ResourceManager.GetString("Menu.UnlockLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used GDI Servers....
        /// </summary>
        internal static string Menu_UsedGDIServers {
            get {
                return ResourceManager.GetString("Menu.UsedGDIServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string Menu_Visibility {
            get {
                return ResourceManager.GetString("Menu.Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string Menu_ZoomIn {
            get {
                return ResourceManager.GetString("Menu.ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string Menu_ZoomOut {
            get {
                return ResourceManager.GetString("Menu.ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string MenuHeader_Apply {
            get {
                return ResourceManager.GetString("MenuHeader.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Views.
        /// </summary>
        internal static string MenuHeader_DataViews {
            get {
                return ResourceManager.GetString("MenuHeader.DataViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MenuHeader_Edit {
            get {
                return ResourceManager.GetString("MenuHeader.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string MenuHeader_Favorites {
            get {
                return ResourceManager.GetString("MenuHeader.Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuHeader_File {
            get {
                return ResourceManager.GetString("MenuHeader.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string MenuHeader_Help {
            get {
                return ResourceManager.GetString("MenuHeader.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string MenuHeader_Insert {
            get {
                return ResourceManager.GetString("MenuHeader.Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string MenuHeader_Options {
            get {
                return ResourceManager.GetString("MenuHeader.Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbars.
        /// </summary>
        internal static string MenuHeader_Toolbars {
            get {
                return ResourceManager.GetString("MenuHeader.Toolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string MenuHeader_View {
            get {
                return ResourceManager.GetString("MenuHeader.View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        internal static string Shape_Arrow {
            get {
                return ResourceManager.GetString("Shape.Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        internal static string Shape_Dimension {
            get {
                return ResourceManager.GetString("Shape.Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        internal static string Shape_Ellipse {
            get {
                return ResourceManager.GetString("Shape.Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freehand.
        /// </summary>
        internal static string Shape_Freehand {
            get {
                return ResourceManager.GetString("Shape.Freehand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Shape_Line {
            get {
                return ResourceManager.GetString("Shape.Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string Shape_Point {
            get {
                return ResourceManager.GetString("Shape.Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        internal static string Shape_Polygon {
            get {
                return ResourceManager.GetString("Shape.Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline.
        /// </summary>
        internal static string Shape_Polyline {
            get {
                return ResourceManager.GetString("Shape.Polyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        internal static string Shape_Rectangle {
            get {
                return ResourceManager.GetString("Shape.Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Shape_Text {
            get {
                return ResourceManager.GetString("Shape.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string String_Back {
            get {
                return ResourceManager.GetString("String.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string String_Choose {
            get {
                return ResourceManager.GetString("String.Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicts.
        /// </summary>
        internal static string String_Conflicts {
            get {
                return ResourceManager.GetString("String.Conflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Features.
        /// </summary>
        internal static string String_CreateNewFeatures {
            get {
                return ResourceManager.GetString("String.CreateNewFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string String_Edit {
            get {
                return ResourceManager.GetString("String.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string String_Editor {
            get {
                return ResourceManager.GetString("String.Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string String_Export {
            get {
                return ResourceManager.GetString("String.Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map (network) folder....
        /// </summary>
        internal static string String_MapNetFolder {
            get {
                return ResourceManager.GetString("String.MapNetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Features.
        /// </summary>
        internal static string String_ModifyFeatures {
            get {
                return ResourceManager.GetString("String.ModifyFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string String_Network {
            get {
                return ResourceManager.GetString("String.Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection ....
        /// </summary>
        internal static string String_NewConnection {
            get {
                return ResourceManager.GetString("String.NewConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string String_Next {
            get {
                return ResourceManager.GetString("String.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Settings.
        /// </summary>
        internal static string String_ProxySettings {
            get {
                return ResourceManager.GetString("String.ProxySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Results.
        /// </summary>
        internal static string String_QueryResults {
            get {
                return ResourceManager.GetString("String.QueryResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string String_Refresh {
            get {
                return ResourceManager.GetString("String.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string String_Selection {
            get {
                return ResourceManager.GetString("String.Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapping.
        /// </summary>
        internal static string String_Snapping {
            get {
                return ResourceManager.GetString("String.Snapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapping Schema.
        /// </summary>
        internal static string String_SnappingSchema {
            get {
                return ResourceManager.GetString("String.SnappingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string String_Source {
            get {
                return ResourceManager.GetString("String.Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string String_Task {
            get {
                return ResourceManager.GetString("String.Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined ....
        /// </summary>
        internal static string String_UserDefined {
            get {
                return ResourceManager.GetString("String.UserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale:.
        /// </summary>
        internal static string Text_Scale {
            get {
                return ResourceManager.GetString("Text.Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string Text_Search {
            get {
                return ResourceManager.GetString("Text.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar Graphics.
        /// </summary>
        internal static string Toolbars_Graphics {
            get {
                return ResourceManager.GetString("Toolbars.Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar Scale.
        /// </summary>
        internal static string Toolbars_Scale {
            get {
                return ResourceManager.GetString("Toolbars.Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar Tools.
        /// </summary>
        internal static string Toolbars_Tools {
            get {
                return ResourceManager.GetString("Toolbars.Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ....
        /// </summary>
        internal static string Tools_About {
            get {
                return ResourceManager.GetString("Tools.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data ....
        /// </summary>
        internal static string Tools_AddData {
            get {
                return ResourceManager.GetString("Tools.AddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        internal static string Tools_ClearSelection {
            get {
                return ResourceManager.GetString("Tools.ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string Tools_CloneLayer {
            get {
                return ResourceManager.GetString("Tools.CloneLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Tools_Copy {
            get {
                return ResourceManager.GetString("Tools.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Tools_Cut {
            get {
                return ResourceManager.GetString("Tools.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Table ....
        /// </summary>
        internal static string Tools_DataTable {
            get {
                return ResourceManager.GetString("Tools.DataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Tools_Delete {
            get {
                return ResourceManager.GetString("Tools.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Editor.
        /// </summary>
        internal static string Tools_Editor_Attributes {
            get {
                return ResourceManager.GetString("Tools.Editor.Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Feature.
        /// </summary>
        internal static string Tools_Editor_Delete {
            get {
                return ResourceManager.GetString("Tools.Editor.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sketch.
        /// </summary>
        internal static string Tools_Editor_DeleteSktech {
            get {
                return ResourceManager.GetString("Tools.Editor.DeleteSktech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Feature/Sketch.
        /// </summary>
        internal static string Tools_Editor_ModifyFeature {
            get {
                return ResourceManager.GetString("Tools.Editor.ModifyFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Feature/Vertex.
        /// </summary>
        internal static string Tools_Editor_NewFeature {
            get {
                return ResourceManager.GetString("Tools.Editor.NewFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Feature.
        /// </summary>
        internal static string Tools_Editor_Store {
            get {
                return ResourceManager.GetString("Tools.Editor.Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Vertices.
        /// </summary>
        internal static string Tools_EditVertices {
            get {
                return ResourceManager.GetString("Tools.EditVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Tools_Exit {
            get {
                return ResourceManager.GetString("Tools.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Features ....
        /// </summary>
        internal static string Tools_ExportFeatures {
            get {
                return ResourceManager.GetString("Tools.ExportFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find ....
        /// </summary>
        internal static string Tools_Find {
            get {
                return ResourceManager.GetString("Tools.Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify.
        /// </summary>
        internal static string Tools_Identify {
            get {
                return ResourceManager.GetString("Tools.Identify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Renderer ....
        /// </summary>
        internal static string Tools_ImportRenderer {
            get {
                return ResourceManager.GetString("Tools.ImportRenderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load ....
        /// </summary>
        internal static string Tools_Load {
            get {
                return ResourceManager.GetString("Tools.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        internal static string Tools_Measure {
            get {
                return ResourceManager.GetString("Tools.Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Tools_New {
            get {
                return ResourceManager.GetString("Tools.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Map.
        /// </summary>
        internal static string Tools_NewMap {
            get {
                return ResourceManager.GetString("Tools.NewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview Map Window.
        /// </summary>
        internal static string Tools_OverViewMap {
            get {
                return ResourceManager.GetString("Tools.OverViewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Settup ....
        /// </summary>
        internal static string Tools_PageSetup {
            get {
                return ResourceManager.GetString("Tools.PageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        internal static string Tools_Pan {
            get {
                return ResourceManager.GetString("Tools.Pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Tools_Paste {
            get {
                return ResourceManager.GetString("Tools.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Schema.
        /// </summary>
        internal static string Tools_PasteSchema {
            get {
                return ResourceManager.GetString("Tools.PasteSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointer.
        /// </summary>
        internal static string Tools_Pointer {
            get {
                return ResourceManager.GetString("Tools.Pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Tools_Print {
            get {
                return ResourceManager.GetString("Tools.Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        internal static string Tools_PrintPreview {
            get {
                return ResourceManager.GetString("Tools.PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties ....
        /// </summary>
        internal static string Tools_Properties {
            get {
                return ResourceManager.GetString("Tools.Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Tools_Refresh {
            get {
                return ResourceManager.GetString("Tools.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Map.
        /// </summary>
        internal static string Tools_RefreshMap {
            get {
                return ResourceManager.GetString("Tools.RefreshMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename ....
        /// </summary>
        internal static string Tools_Rename {
            get {
                return ResourceManager.GetString("Tools.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Tools_Save {
            get {
                return ResourceManager.GetString("Tools.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As ....
        /// </summary>
        internal static string Tools_SaveAs {
            get {
                return ResourceManager.GetString("Tools.SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Tools_Select {
            get {
                return ResourceManager.GetString("Tools.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select By Attributes.
        /// </summary>
        internal static string Tools_SelectByAttributes {
            get {
                return ResourceManager.GetString("Tools.SelectByAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend Window.
        /// </summary>
        internal static string Tools_ShowLegend {
            get {
                return ResourceManager.GetString("Tools.ShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom/Pan.
        /// </summary>
        internal static string Tools_SmartNavigation {
            get {
                return ResourceManager.GetString("Tools.SmartNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split With Filter ....
        /// </summary>
        internal static string Tools_SplitWithFilter {
            get {
                return ResourceManager.GetString("Tools.SplitWithFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Of Contens.
        /// </summary>
        internal static string Tools_TOC {
            get {
                return ResourceManager.GetString("Tools.TOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To Coordinate.
        /// </summary>
        internal static string Tools_XY {
            get {
                return ResourceManager.GetString("Tools.XY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Tools_ZoomBack {
            get {
                return ResourceManager.GetString("Tools.ZoomBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string Tools_ZoomForward {
            get {
                return ResourceManager.GetString("Tools.ZoomForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string Tools_ZoomIn {
            get {
                return ResourceManager.GetString("Tools.ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In Static.
        /// </summary>
        internal static string Tools_ZoomInStatic {
            get {
                return ResourceManager.GetString("Tools.ZoomInStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string Tools_ZoomOut {
            get {
                return ResourceManager.GetString("Tools.ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out Static.
        /// </summary>
        internal static string Tools_ZoomOutStatic {
            get {
                return ResourceManager.GetString("Tools.ZoomOutStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To Full Extent.
        /// </summary>
        internal static string Tools_ZoomToFullExtent {
            get {
                return ResourceManager.GetString("Tools.ZoomToFullExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To Layer.
        /// </summary>
        internal static string Tools_ZoomToLayer {
            get {
                return ResourceManager.GetString("Tools.ZoomToLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To Selection.
        /// </summary>
        internal static string Tools_ZoomToSelection {
            get {
                return ResourceManager.GetString("Tools.ZoomToSelection", resourceCulture);
            }
        }
    }
}
