//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo_v3.OGR {

public enum FieldSubType {
  OFSTNone = 0,
  OFSTBoolean = 1,
  OFSTInt16 = 2,
  OFSTFloat32 = 3,
  OFSTJSON = 4,
  OFSTUUID = 5
}

}
