//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gView.Win.Explorer.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gView.Win.Explorer.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap arrow_back_16 {
            get {
                object obj = ResourceManager.GetObject("arrow_back_16", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap arrow_back_161 {
            get {
                object obj = ResourceManager.GetObject("arrow_back_161", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap arrow_back_24 {
            get {
                object obj = ResourceManager.GetObject("arrow_back_24", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap arrow_forward_16 {
            get {
                object obj = ResourceManager.GetObject("arrow_forward_16", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap arrow_left24 {
            get {
                object obj = ResourceManager.GetObject("arrow_left24", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap arrow_right24 {
            get {
                object obj = ResourceManager.GetObject("arrow_right24", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap back1 {
            get {
                object obj = ResourceManager.GetObject("back1", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap explorer_back1 {
            get {
                object obj = ResourceManager.GetObject("explorer_back1", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap explorer_back2 {
            get {
                object obj = ResourceManager.GetObject("explorer_back2", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap explorer_back3 {
            get {
                object obj = ResourceManager.GetObject("explorer_back3", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap explorer_back4 {
            get {
                object obj = ResourceManager.GetObject("explorer_back4", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap ExplorerStyle {
            get {
                object obj = ResourceManager.GetObject("ExplorerStyle", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap ExplorerStyle_details {
            get {
                object obj = ResourceManager.GetObject("ExplorerStyle_details", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap ExplorerStyle_list {
            get {
                object obj = ResourceManager.GetObject("ExplorerStyle_list", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap folder_go {
            get {
                object obj = ResourceManager.GetObject("folder_go", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap folder_heart {
            get {
                object obj = ResourceManager.GetObject("folder_heart", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap menu_back1 {
            get {
                object obj = ResourceManager.GetObject("menu_back1", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap menu_back11 {
            get {
                object obj = ResourceManager.GetObject("menu_back11", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap netdirectory {
            get {
                object obj = ResourceManager.GetObject("netdirectory", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap netdirectory1 {
            get {
                object obj = ResourceManager.GetObject("netdirectory1", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap pfeil_r_s {
            get {
                object obj = ResourceManager.GetObject("pfeil_r_s", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap pfeil_s {
            get {
                object obj = ResourceManager.GetObject("pfeil_s", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap tree_minus {
            get {
                object obj = ResourceManager.GetObject("tree_minus", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type global::System.Drawing.Bitmap.
        /// </summary>
        internal static global::System.Drawing.Bitmap tree_plus {
            get {
                object obj = ResourceManager.GetObject("tree_plus", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
    }
}
